<a href="https://colab.research.google.com/github/mgonzal1/nma_wombat_connectivy_project/blob/Eve/connectivity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#@title import matplotlib and set defaults
from matplotlib import rcParams 
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
rcParams['figure.figsize'] = [20, 4]
rcParams['font.size'] =15
rcParams['axes.spines.top'] = False
rcParams['axes.spines.right'] = False
rcParams['figure.autolayout'] = True

In [2]:
#@title Data retrieval
import os, requests

fname = []
for j in range(3):
  fname.append('steinmetz_part%d.npz'%j)
url = ["https://osf.io/agvxh/download"]
url.append("https://osf.io/uv3mw/download")
url.append("https://osf.io/ehmw2/download")

for j in range(len(url)):
  if not os.path.isfile(fname[j]):
    try:
      r = requests.get(url[j])
    except requests.ConnectionError:
      print("!!! Failed to download data !!!")
    else:
      if r.status_code != requests.codes.ok:
        print("!!! Failed to download data !!!")
      else:
        with open(fname[j], "wb") as fid:
          fid.write(r.content)



alldat = np.array([])
for j in range(len(fname)):
  alldat = np.hstack((alldat, np.load('steinmetz_part%d.npz'%j, allow_pickle=True)['dat']))

In [3]:
n_sessions = 39
trial_time = 2.5
def get_trainning_set():
  """
  Get a subset of alldat for trainning purposes.

  Returns:
    map: dat['spks']: neurons by trials by time bins. Time bin = 10ms.
         dat['brain_area']: brain area for each neuron recorded.
         dat['contrast_right']: contrast level for the right stimulus, which is always contralateral to the recorded brain areas.
         dat['contrast_left']: contrast level for left stimulus.
         dat['response']: which side the response was (-1, 0, 1). Choices for the right stimulus are -1.
         dat['response_times']: when the response was registered, which has to be after the go cue. The mouse can turn the wheel before the go cue (and always does!).
         dat['wheel']: exact position of the wheel that the mice uses to make a response, binned at 10ms.
         dat['pupil']: pupil area (noisy, because pupil is very small).
         dat['lfp']: recording of the local field potential in each brain area from this experiment, binned at 10ms.
         dat['brain_area_lfp']: brain area names for the LFP channels.
  """
  # Functions to split data and get a subset. If condition of areas  
  tranning_set = alldat
  return trainning_set


In [4]:
def get_validation_set():
  """
  Get a subset of alldat for validation purposes. This should be ~5%-10% of all the data.

  Returns:
    map: dat['spks']: neurons by trials by time bins. Time bin = 10ms.
         dat['brain_area']: brain area for each neuron recorded.
         dat['contrast_right']: contrast level for the right stimulus, which is always contralateral to the recorded brain areas.
         dat['contrast_left']: contrast level for left stimulus.
         dat['response']: which side the response was (-1, 0, 1). Choices for the right stimulus are -1.
         dat['response_times']: when the response was registered, which has to be after the go cue. The mouse can turn the wheel before the go cue (and always does!).
         dat['wheel']: exact position of the wheel that the mice uses to make a response, binned at 10ms.
         dat['pupil']: pupil area (noisy, because pupil is very small).
         dat['lfp']: recording of the local field potential in each brain area from this experiment, binned at 10ms.
         dat['brain_area_lfp']: brain area names for the LFP channels.
  """
  
  # Functions to split data and get a subset 
  validation_set = alldat
  return validation_set


In [5]:
#@title Data loading

alldat = np.array([])
for j in range(len(fname)):
  alldat = np.hstack((alldat, np.load('steinmetz_part%d.npz'%j, allow_pickle=True)['dat']))


In [ ]:
# select sesssion 12
ses = 11
dat = alldat[ses]
print(dat.keys())

#V=X(A1)
#X=Stim[nTrials]
#V=[ntrialsxnNeurons]
#A1=[2xnNeurons]

regions = ["VISa", "VISam", "VISl", "VISp", "VISpm", "VISrl", "ACA", "MOs", "PL", 
                "ORB", "MOp", "GPe", "SNr", "LD", "LP", "CP"]

nareas = 16 # 16 visual areas
NN = len(dat['brain_area']) # number of neurons
barea = nareas * np.ones(NN, ) 

for j in range(nareas):
  barea[np.isin(dat['brain_area'], regions[j])] = j # assign a number to each region



In [ ]:
Mos= dat['spks'][barea==3]
Mos
print (Mos)


In [ ]:
vis_right = dat['contrast_right'] # 0 - low - high
vis_left = dat['contrast_left'] # 0 - low - high

In [44]:
print (n_sessions)

39


In [ ]:
dt = dat['bin_size'] # binning at 10 ms
NT = dat['spks'].shape[-1]


dat['spks'][barea==j]

 


def get_visual_spikes(data_set):

  n_sessions
  
  for session in range(n_sessions):
  temp = alldat[session]['spks'][:,:,:].sum(axis=2)/trial_time
  n_neurons, n_trials = temp.shape
  fr.append(temp)
  n_trials_session.append(n_trials)
  n_neurons_session.append(n_neurons) 
n_trials_session = np.array(n_trials_session)
n_neurons_session = np.array(n_neurons_session)




In [ ]:
np.logical_and(vis_left==0, vis_right>0)


In [39]:
Mos= dat['spks'][barea==8]
aca
print (aca)

[[[0 1 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 1 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [9]:
def get_visual_stim (data_set):

  for 

dat['spks'][barea==j][:,np.logical_and(vis_left==0, vis_right>0)].mean
dat['spks'][barea==j][:,np.logical_and(vis_left>0 , vis_right==0)].mean
dat['spks'][barea==j][:,np.logical_and(vis_left==0 , vis_right==0)].mean
dat['spks'][barea==j][:,np.logical_and(vis_left>0, vis_right>0)].mean 
 
  

               
  return



SyntaxError: ignored

In [ ]:
def get_motor_spikes(data_set):
  return



In [ ]:
def get_stimulus(data_set):
  """
   Args: 
      data_set: (map) Subset of alldat
      
   Returns:
      stim_right: (np.array) contrast level for the right stimulus, which is always contralateral to the recorded brain areas.
      stim_left: (np.array) contrast level for left stimulus.
  """
  stim_right = np.array(data_set['contrast_right'])
  stim_left  = np.array(data_set['contrast_left'])
  return stim_right, stim_left


In [ ]:
  return

def get_decision(data_set):
  return